service: serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  sample:
    handler: handler.sample
    events:
      - http:
          path: sample
          method: GET

  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: POST

  sign_in_with_google:
    handler: handler.sign_in_with_google
    events:
      - http:
          path: sign_in_with_google
          method: POST
